services:
- type: web
  name: xc
  plan: free
  env: docker
  autoDeploy: false
  healthCheckPath: /dashboard
  envVars:
  - key: DATABASE_URL
    fromDatabase:
      name: xc
      property: connectionString
  - key: PORT
    value: 8080
databases:
- name: xc
  plan: free
